website/Lernplattform/urls.py
from django import views
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
import django.contrib.auth.views
from . import views

app_name = 'Lernplattform'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    # path('login/', django.contrib.auth.views.LoginView.as_view(), {'template_name' : 'login.html'}, name='login'),
    path('fragebogen/', views.fragebogen, name='fragebogen'),
    path('fragebogen/details/<int:pk>',
         views.fragebogenDetails, name='fragebogenDetails'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from Lernplattform import urls

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('Lernplattform.urls')),
    path('Lernplattform/', include(('Lernplattform.urls', 'Lernplattform'), namespace='Lernplattform')),
]

website/Lernplattform/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class Katalog(models.Model):
    katalog_name = models.CharField(max_length=200)

    def __str__(self):
        return self.katalog_name


class Frage(models.Model):
    LEICHT = "Leicht"
    MITTEL = "Mittel"
    SCHWER = "Schwer"
    SCHWIERIGKEITSGRAD_AUSWAHL = [
        (LEICHT, 1),
        (MITTEL, 2),
        (SCHWER, 3)
    ]
    frage = models.CharField(max_length=200)
    antwort1 = models.CharField(max_length=200)
    antwort2 = models.CharField(max_length=200)
    antwort3 = models.CharField(max_length=200)
    antwort4 = models.CharField(max_length=200)
    richtige_antwort = models.CharField(max_length=200)
    katalog = models.ForeignKey(Katalog, on_delete=models.CASCADE)
    schwierigkeitsgrad = models.CharField(
        max_length=10,
        choices=SCHWIERIGKEITSGRAD_AUSWAHL,
        default=LEICHT
    )

    def __str__(self):
        return self.frage


class User_Abs(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    password = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        abstract = True


class Teilnehmer(User_Abs):
    abgeschlossene_fragebogen = models.ManyToManyField(Frage, blank=True)


class Admin(User_Abs):
    pass


class Fragebogen(models.Model):
    fragebogen_name = models.CharField(max_length=200)
    katalog = models.ForeignKey(Katalog, on_delete=models.CASCADE)
    fragen = models.ManyToManyField(Frage, blank=True)
    teilnehmer_liste = models.ManyToManyField(Teilnehmer, blank=True)

    def __str__(self):
        return self.fragebogen_name

website/Lernplattform/views.py
from queue import Empty
from django.shortcuts import render
from .models import Fragebogen


# Create your views here.


def index(request):
    return render(request, 'index.html')

def login(request):
    return render(request, 'login.html')

    
def fragebogen(request):
    bogen = Fragebogen.objects.all()
    return render(request, 'fragebogen_liste.html', {'bogen': bogen})


def fragebogenDetails(request, pk):
    bogen = Fragebogen.objects.get(id=pk)
    return render(request, 'fragebogen_details.html', {'bogen': bogen})

website/Lernplattform/templates/fragebogen_details.html
{% extends 'mainTemplate.html' %}
{% load static %}
{% block title %}Fragebogen{% endblock title %}
{% block link %}
<link rel="stylesheet" href="{% static 'styles/styles.css' %}">
<script src="{% static 'script/fragebogen_liste.js' %}"></script>
{% endblock link %}


{% block content %}

<div class="container">

<div class="card text-white bg-dark">
      <div class="card-body">
        <h4 class="card-title">{{ bogen.fragebogen_name }}</h4>
        <p class="card-text">{{ bogen.katalog }}</p>  
      </div>
    </div>

    {% for frage in bogen.fragen.all %}
    <div class="card text-black bg-light">
      <div class="card-body">
        <h4 class="card-title">{{ frage }}</h4>
      </a>
    </div>
    {% endfor %}
    
    </div>
    
    
    
    
    
    
  </div>
  
  
  {% endblock content %}
  
  
  
  <!-- <button id="{{ bogen.id }}" class="btn-primary" href="{% url 'Lernplattform:fragebogenDetails' fragebogen.id %}" onclick=window.location.href="{% url 'fragebogenDetails' fragebogen.id %}" type="button">Details</button> -->

website/Lernplattform/templates/fragebogen_liste.html
{% extends 'mainTemplate.html' %}
{% load static %}
{% block title %}Fragebogen{% endblock title %}
{% block link %}
<link rel="stylesheet" href="{% static 'styles/styles.css' %}">
<script src="{% static 'script/fragebogen_liste.js' %}"></script>
{% endblock link %}


{% block content %}

<div class="container">


    {% for fragebogen in bogen %}

    <div class="card text-white bg-dark">
      <div class="card-body">
        <h4 class="card-title">{{ fragebogen.fragebogen_name }}</h4>
        <p class="card-text">{{ fragebogen.katalog }}</p>
        <a href="{% url 'Lernplattform:fragebogenDetails' fragebogen.pk%}">
          <h1>GEILO</h1>
        </a>
      </div>
    </div>
    
    {% endfor %}



</div>
<script>
  let btns = document.getElementsByClassName("card-btn")
  
  Array.from(btns).forEach(x => x.addEventListener("click", function(){
    var id = this.id;
    var url = this.getAttribute("href");
    window.location.href = url;
  }));
</script>

{% endblock content %}

website/Lernplattform/templates/index.html
{% extends 'mainTemplate.html' %}
{% load static %}
{% block title %}Index{% endblock title %}
{% block link %}
<link rel="stylesheet" href="{% static  'styles/styles.css'%}">
{% endblock link %}





{% block content %}
    <h1>index</h1>
{% endblock content %}

website/Lernplattform/templates/login.html
{% extends 'mainTemplate.html' %}
{% load static %}
{% block title %}Anmeldung{% endblock title %}
{% block link %}
<link rel="stylesheet" href="{% static 'styles/styles.css' %}">
<script src="{% static 'script/fragebogen_liste.js' %}"></script>
{% endblock link %}


{% block content %}

<div class="container">
    <h2>Einloggen</h2>
    <form action="post" method="post" enctype="multipart/form-data">{% csrf_token %}
        <input type="email" name="email" placeholder="E-Mail">
        <input type="password" name="password" placeholder="Passwort">
        <button type="submit">Einloggen</button>

    </form>
</div>














{% endblock content %}

website/Lernplattform/templates/mainTemplate.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Title{% endblock title %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"  integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'styles/template.css' %}">
    
    {% block link %}
    {% endblock link %}
</head>
<body>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="navbar">
        <a class="navbar-brand" href="#">Lernplattform</a>
        <button class="navbar-toggler d-lg-none" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavId" aria-controls="collapsibleNavId"
        aria-expanded="false" aria-label="Toggle navigation"></button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
            <ul class="navbar-nav me-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'Lernplattform:index' %}">Home <span class="visually-hidden">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Lernplattform:fragebogen' %}">Fragebogen</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="">Platzhalter</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Account</a>
                    <div class="dropdown-menu" aria-labelledby="dropdownId">
                        <a class="dropdown-item" href="#">Details</a>
                        <a class="dropdown-item" href="{% url 'Lernplattform:login' %}">Anmelden</a>
                    </div>
                </li>
            </ul>
            <form class="d-flex my-2 my-lg-0 visually-hidden">
                <input class="form-control me-sm-2" type="text" placeholder="Suchen">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Suchen</button>
            </form>
        </div>
    </nav>
    
    {% block post-navbar %}
    {% endblock post-navbar %}
    
    
    {% block content %}
    {% endblock content %}
    
    {% block pre-footer %}
    {% endblock pre-footer %}
    
    <footer class="bg-light text-center text-lg-start" id="footer">
        <div class="container p-4">
            <div class="row">
                <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
                    <h5 class="text-uppercase">Links</h5>
                    <p>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae ea maxime sunt fugit, distinctio tempore. Labore, temporibus? Dolor possimus qui, corporis repellat mollitia eveniet, exercitationem autem repudiandae ducimus corrupti quidem.
                    </p>
                </div>
                <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
                    <h5 class="text-uppercase">Links</h5>
                    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fugit inventore ipsa vitae doloremque, earum quibusdam quisquam consequuntur quo aut maxime porro ullam eos explicabo aliquid placeat ipsum incidunt omnis ea.
                    </p>
                </div>
            </div>
        </div>
        <div class="text-center p-3">
            <p class="text-muted">
                © 2020 EvilInc.
            </p>
        </div>
    </footer>
    
    
    <!-- Bootstrap JavaScript Libraries -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    
</body>
</html>